[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/sitemap"
  status = 200

[[redirects]]
  from = "/_posts/index.json"
  to = "/.netlify/functions/content/posts"
  status = 200

[[redirects]]
  from = "/_artworks/index.json"
  to = "/.netlify/functions/content/artworks"
  status = 200

[[redirects]]
  from = "/_videos/index.json"
  to = "/.netlify/functions/content/videos"
  status = 200

[[redirects]]
  from = "/_seo/index.json"
  to = "/.netlify/functions/content/seo"
  status = 200
