backend:
  name: github
  repo: pathompongwk-hub/pmpromo-web
  branch: main
  base_url: https://pmpromo-web.pathompong-wk.workers.dev
  auth_endpoint: /auth

media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "บทความ"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "หัวข้อ", name: "title", widget: "string" }
      - { label: "หมวดหมู่", name: "category", widget: "string" }
      - { label: "วันที่", name: "date", widget: "datetime" }
      - { label: "เวลาอ่าน", name: "readtime", widget: "string" }
      - { label: "เนื้อหา", name: "body", widget: "markdown" }
  - name: "works"
    label: "ผลงาน"
    folder: "_works"
    create: true
    fields:
      - { label: "ชื่อโปรเจกต์", name: "title", widget: "string" }
      - { label: "หมวดหมู่", name: "category", widget: "string" }
      - { label: "รายละเอียด", name: "description", widget: "text" }
      - { label: "รูปภาพ", name: "image", widget: "image", required: false }
